
services:
  db:
    image: mysql:8.0.40
    container_name: hotel-booking
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Mysql
      MYSQL_DATABASE: hotel_booking_db
    volumes:
      - hotel_booking_vol:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d

volumes:
  hotel_booking_vol:
